### ISSUE TITLE
Unable to delete by filter values

### ISSUE THREAD

**Issue by sheetalkumar105** [ashokvishwakarma/dgraph-orm#3]
Allow delete like this:

    User.delete({
       filter: {
        email: 'akvlko@gmail.com',
        name: 'Ashok Vishwakarma'
       }
    });

**Comment by ashokvishwakarma** [comment]
Added delete by conditions in version 1.1.2

```
/**
 * Delete by condition
 * 
 * Will delete all the matching users (whose name is Ashok in this case)
 */
User.delete({
  name: 'Ashok'
});
```
