### ISSUE TITLE
Use in native JS

### ISSUE THREAD

**Issue by paulrostorp** [ashokvishwakarma/dgraph-orm#6]
Package does not work if you want to use in native JS; throws this error: 
Error: Cannot find module 'babel-runtime/regenerator'

**Comment by ashokvishwakarma** [comment]
What do you mean by native js? In browser?

**Comment by paulrostorp** [comment]
I mean common JS, not ES6. I'm using via require() vs. import in your examples.

**Comment by ashokvishwakarma** [comment]
@paulrostorp Thanks for your feedback, will update the same. You can also send a PR if you are interested.

**Comment by ashokvishwakarma** [comment]
Fixed in V 1.1.3
