### ISSUE TITLE
Implement TypeORM style entity definition

### ISSUE THREAD

**Issue by ISNIT0** [ashokvishwakarma/dgraph-orm#8]
E.g. http://typeorm.io

Instead of the example on the README, something like:
```typescript
import {Entity, Property} from "dgraph-orm";

@Entity()
export class User {
    @Property()
    firstName: string;

    @Property()
    lastName: string;

    @Property()
    age: number;
}
```

Not sure how this would work in a more complex case.
Would love to help implement this

**Comment by ashokvishwakarma** [comment]
Let me look into the same.

**Comment by GoodFaithParadigm8** [comment]
I'd shoot for
```typescript
import {Entity, Property} from "dgraph-orm";

@Entity()
export class User {
    @Node()
    firstName: string;

    @Node()
    lastName: string;

    @Node()
    age: number;
}
```
as opposed to Column() in typeORM, but +1.

**Comment by GoodFaithParadigm8** [comment]
Suppose it's all how the data gets mapped to the underlying database, but upon further review, my previous suggestion may not be the most ideal naming convention.  { Entity, Property } turns out to not be such a bad naming convention.


```typescript
import { Node, Predicate } from "dgraph-orm";

@Node()  // the subject
export class User {
    @PrimaryGeneratedColoumn('uuid')
     id: string;

    @Predicate()
    firstName: string;

    @Predicate()
    lastName: string;

    @Predicate()
    age: number;
}
```

**Comment by sessionboy** [comment]
Any update ?

**Comment by ashokvishwakarma** [comment]
As of now, I am fixing the issues and adding the support for latest version of Dgraph.

TypeORM style is in pipeline and will push a release soon.

**Comment by MentalGear** [comment]
Awesome that full TypeORM support is coming, @avishwakarma ! Any updates to share?
